import { SERVER_TEMPLATE } from './templates/server-template';

/**
 * Ultimate Web Engine v4.0 - Full-Stack Generator
 * Elite aesthetics (Glass, Neon, Deep Layers) + Express Backend
 */
export class Generator {
    constructor(config) {
        this.config = config;
        this.files = {};
    }

    generate() {
        // 1. Frontend
        this.createIndexHtml();
        this.createGlobalStyles();
        this.createScripts();

        // 2. Backend (Always generated in v4)
        this.files['server.js'] = SERVER_TEMPLATE.trim();
        this.files['package.json'] = JSON.stringify({
            name: "generated-app",
            version: "1.0.0",
            description: "Full-stack site generated by WebBuilder v4.0",
            main: "server.js",
            scripts: {
                start: "node server.js",
                dev: "nodemon server.js"
            },
            dependencies: {
                express: "^4.18.2",
                cors: "^2.8.5",
                dotenv: "^16.0.3"
            }
        }, null, 2);

        this.files['.env'] = "PORT=5000\nNODE_ENV=production";

        return this.files;
    }

    createIndexHtml() {
        const { meta, content } = this.config;
        const sectionsHtml = content.map(section => this.renderSection(section)).join('\n');

        this.files['index.html'] = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${meta.title}</title>
    <meta name="description" content="${meta.description}">
    
    <!-- Elite Typography -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@300;400;500;600&family=Space+Grotesk:wght@300;500;700&display=swap" rel="stylesheet">
    
    <!-- Professional Assets -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/lucide@latest"></script>
    
    <link rel="stylesheet" href="style.css">
</head>
<body class="theme-${meta.theme.mode}">
    <div class="glow-canvas"></div>
    <div class="app-wrapper">
        ${this.renderNavbar()}
        <main>
            ${sectionsHtml}
        </main>
        ${this.renderFooter()}
    </div>
    
    ${this.config.isPremium ? '' : this.renderWatermark()}
    
    <!-- Logic Core -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>
    <script src="script.js"></script>
</body>
</html>`.trim();
    }

    renderNavbar() {
        return `
    <nav class="elite-nav glass-blur">
        <div class="container nav-flex">
            <a href="#" class="logo-neon">${this.config.meta.title}</a>
            <div class="nav-links">
                ${this.config.content.filter(s => s.id).map(s => `<a href="#${s.id}" class="nav-item">${s.type.toUpperCase()}</a>`).join('')}
                <a href="#cta" class="btn btn-neon btn-sm">Get Started</a>
            </div>
        </div>
    </nav>`;
    }

    renderFooter() {
        return `
    <footer class="elite-footer">
        <div class="container">
            <div class="footer-grid">
                <div class="footer-info">
                    <h3 class="logo-neon">${this.config.meta.title}</h3>
                    <p>${this.config.meta.description}</p>
                </div>
            </div>
            <div class="footer-copy">
                <p>&copy; ${new Date().getFullYear()} ${this.config.meta.title}. Powered by Engine v4.</p>
            </div>
        </div>
    </footer>`;
    }

    renderWatermark() {
        return `<div class="elite-watermark">
        <span class="neon-dot"></span>
        Built with <strong>WebBuilder Elite</strong>
    </div>`;
    }

    renderSection(section) {
        const animation = section.animation || 'fade-up';
        const idAttr = section.id ? `id="${section.id}"` : '';
        const styleAttr = this.getSectionStyles(section);

        switch (section.type) {
            case 'hero':
                return `
    <section class="section-hero" ${idAttr} style="${styleAttr}">
        <div class="container hero-grid">
            <div class="content-box" data-aos="${animation}">
                <div class="elite-badge">NEW v4.0</div>
                <h1 class="text-display">${section.data.headline}</h1>
                <p class="text-lead">${section.data.subheadline}</p>
                <div class="action-row">
                    <a href="${section.data.ctaLink}" class="btn btn-neon btn-lg shadow-glow">${section.data.ctaText}</a>
                    <a href="#" class="btn btn-outline btn-lg">Explore Logic</a>
                </div>
            </div>
            <div class="visual-box" data-aos="zoom-in" data-aos-delay="200">
                <div class="floating-glass">
                    ${section.data.imageUrl ? `<img src="${section.data.imageUrl}" alt="Visual">` : '<div class="neon-card-placeholder"></div>'}
                </div>
            </div>
        </div>
        <div class="ambient-glow"></div>
    </section>`;

            case 'features':
                return `
    <section class="section-features" ${idAttr} style="${styleAttr}" data-aos="${animation}">
        <div class="container">
            <div class="section-head text-center">
                <h2 class="text-title">${section.data.title}</h2>
            </div>
            <div class="elite-grid">
                ${(section.data.items || []).map((item, i) => `
                <div class="elite-card hov-lift" data-aos="fade-up" data-aos-delay="${i * 100}">
                    <div class="icon-neon"><i data-lucide="${item.icon || 'zap'}"></i></div>
                    <h3>${item.title}</h3>
                    <p>${item.desc}</p>
                </div>`).join('')}
            </div>
        </div>
    </section>`;

            // More section types can be expanded here...
            default:
                return `<section class="placeholder" ${idAttr}>Custom Section: ${section.type}</section>`;
        }
    }

    getSectionStyles(section) {
        let styles = [];
        if (section.styles) {
            if (section.styles.backgroundColor) styles.push(`background-color: ${section.styles.backgroundColor}`);
            if (section.styles.textColor) styles.push(`color: ${section.styles.textColor}`);
            if (section.styles.padding) styles.push(`padding: ${section.styles.padding}px 0`);
        }
        return styles.join(';');
    }

    createGlobalStyles() {
        const { meta } = this.config;
        const theme = meta?.theme || {};
        const primary = theme.primary || '#6366f1';

        this.files['style.css'] = `
:root {
    --primary: ${primary};
    --primary-rgb: ${this.hexToRgb(primary)};
    --accent: #0ea5e9;
    --accent-rgb: 14, 165, 233;
    
    /* Ultimate Dark Motif */
    --bg-deep: #020617;
    --bg-glass: rgba(15, 23, 42, 0.65);
    --text-high: #f8fafc;
    --text-mid: #94a3b8;
    --border-light: rgba(255, 255, 255, 0.06);
    --border-neon: rgba(var(--primary-rgb), 0.3);
    
    --font-heading: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif;
    --font-body: 'Inter', sans-serif;
}

/* Base resets & depth */
* { margin: 0; padding: 0; box-sizing: border-box; }
html { scroll-behavior: smooth; }
body { 
    background: var(--bg-deep); 
    color: var(--text-high); 
    font-family: var(--font-body); 
    overflow-x: hidden;
    line-height: 1.6;
}

.container { max-width: 1240px; margin: 0 auto; padding: 0 2rem; }
.glass-blur { backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px); border-bottom: 1px solid var(--border-light); }

/* Typography Elite */
.text-display { font-family: var(--font-heading); font-size: clamp(3.5rem, 8vw, 6rem); font-weight: 700; line-height: 1; letter-spacing: -0.04em; margin-bottom: 1.5rem; }
.text-title { font-family: var(--font-heading); font-size: clamp(2.5rem, 5vw, 4rem); font-weight: 700; margin-bottom: 1.5rem; background: linear-gradient(to right, #fff, var(--text-mid)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.text-lead { font-size: 1.25rem; color: var(--text-mid); margin-bottom: 3rem; max-width: 650px; }

/* Buttons Neon */
.btn { display: inline-flex; align-items: center; justify-content: center; padding: 1rem 2.5rem; border-radius: 12px; font-weight: 700; cursor: pointer; transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1); text-decoration: none; border: none; font-size: 1rem; }
.btn-neon { background: var(--primary); color: white; box-shadow: 0 10px 30px -5px rgba(var(--primary-rgb), 0.5); }
.btn-neon:hover { transform: translateY(-4px); box-shadow: 0 20px 40px -10px rgba(var(--primary-rgb), 0.6), 0 0 20px rgba(var(--primary-rgb), 0.3); }
.btn-outline { border: 1.5px solid var(--border-light); color: white; background: transparent; }
.btn-outline:hover { background: rgba(255,255,255,0.05); border-color: var(--text-mid); }
.btn-sm { padding: 0.6rem 1.5rem; font-size: 0.875rem; }

/* Elite Nav */
.elite-nav { position: fixed; top: 0; width: 100%; z-index: 1000; height: 90px; }
.nav-flex { height: 100%; display: flex; justify-content: space-between; align-items: center; }
.logo-neon { font-family: var(--font-heading); font-weight: 800; font-size: 1.75rem; color: white; text-decoration: none; letter-spacing: -0.02em; }
.nav-links { display: flex; gap: 2.5rem; align-items: center; }
.nav-item { text-decoration: none; color: var(--text-mid); font-weight: 600; font-size: 0.9rem; transition: 0.3s; }
.nav-item:hover { color: white; }

/* Hero Section Elite */
.section-hero { position: relative; padding: 220px 0 140px; overflow: hidden; }
.hero-grid { display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 6rem; align-items: center; }
.elite-badge { display: inline-block; padding: 0.5rem 1rem; background: rgba(var(--primary-rgb), 0.1); border: 1px solid var(--border-neon); border-radius: 99px; color: var(--primary); font-size: 0.75rem; font-weight: 800; letter-spacing: 0.1em; margin-bottom: 1.5rem; }
.action-row { display: flex; gap: 1.5rem; }

.floating-glass { position: relative; border-radius: 24px; border: 1px solid var(--border-light); background: var(--bg-glass); padding: 1.5rem; box-shadow: 0 40px 80px rgba(0,0,0,0.4); animation: eliteFloat 6s infinite ease-in-out; }
.floating-glass img { width: 100%; border-radius: 12px; }
.neon-card-placeholder { height: 400px; width: 100%; background: linear-gradient(45deg, #0f172a, #1e293b); border-radius: 12px; border: 1.5px solid var(--border-neon); position: relative; overflow: hidden; }
.neon-card-placeholder::after { content: ''; position: absolute; inset: -20%; background: radial-gradient(circle, rgba(var(--primary-rgb), 0.2), transparent 70%); animation: pulseNeon 4s infinite; }

@keyframes eliteFloat { 0%, 100% { transform: translateY(0) rotate(0); } 50% { transform: translateY(-25px) rotate(1deg); } }
@keyframes pulseNeon { 0%, 100% { opacity: 0.5; } 50% { opacity: 1; } }

/* Features Section Elite */
.section-features { padding: 120px 0; background: #020617; }
.elite-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 2.5rem; margin-top: 5rem; }
.elite-card { padding: 3.5rem; background: var(--bg-glass); border: 1px solid var(--border-light); border-radius: 24px; transition: 0.5s; position: relative; overflow: hidden; }
.elite-card::before { content: ''; position: absolute; top: 0; left: 0; width: 100%; height: 2px; background: linear-gradient(90deg, transparent, var(--primary), transparent); transform: translateX(-100%); transition: 0.5s; }
.elite-card:hover::before { transform: translateX(100%); }
.elite-card:hover { border-color: var(--border-neon); transform: translateY(-10px); background: rgba(15, 23, 42, 0.85); box-shadow: 0 30px 60px -10px rgba(0,0,0,0.5); }
.icon-neon { width: 64px; height: 64px; background: rgba(var(--primary-rgb), 0.1); color: var(--primary); border-radius: 18px; display: flex; align-items: center; justify-content: center; margin-bottom: 2rem; border: 1px solid var(--border-neon); }
.elite-card h3 { font-size: 1.5rem; margin-bottom: 1rem; font-family: var(--font-heading); }
.elite-card p { color: var(--text-mid); }

/* Ambient Background */
.glow-canvas { position: fixed; inset: 0; pointer-events: none; z-index: -1; background: radial-gradient(circle at 20% 30%, rgba(var(--primary-rgb), 0.15) 0%, transparent 40%), radial-gradient(circle at 80% 70%, rgba(var(--accent-rgb, 0, 242, 255), 0.05) 0%, transparent 40%); }

/* Watermark Elite */
.elite-watermark { position: fixed; bottom: 30px; left: 30px; background: rgba(0,0,0,0.9); border: 1px solid var(--border-light); padding: 0.75rem 1.25rem; border-radius: 100px; font-size: 0.8rem; z-index: 9999; display: flex; align-items: center; gap: 10px; color: var(--text-mid); backdrop-filter: blur(10px); }
.neon-dot { width: 6px; height: 6px; background: var(--primary); border-radius: 50%; box-shadow: 0 0 10px var(--primary); animation: blink 2s infinite; }
@keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0.3; } }

@media (max-width: 968px) {
    .container { padding: 0 1.5rem; }
    .hero-grid { grid-template-columns: 1fr; gap: 4rem; text-align: center; }
    .text-lead { margin-inline: auto; }
    .action-row { justify-content: center; }
}
`.trim();
    }

    createScripts() {
        this.files['script.js'] = `
lucide.createIcons();
AOS.init({ duration: 1000, once: true, easing: 'ease-out-cubic' });

// GSAP Ambient Interactions
gsap.registerPlugin(ScrollTrigger);

// Parallax effects
gsap.to(".floating-glass", {
    y: -50,
    scrollTrigger: {
        trigger: ".section-hero",
        start: "top top",
        end: "bottom top",
        scrub: true
    }
});

console.log("Elite Engine v4.0 Active");
`.trim();
    }

    hexToRgb(hex) {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result ? `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}` : '99, 102, 241';
    }
}
